server:
  port: 3344
spring:
  application:
    name: configserver
  profiles:
    active: git #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2568808909/movie-config.git
      label: master
